import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the "Porto for AI" docs instance.
// Autogenerated from the docs-ai/ folder structure.
const sidebars: SidebarsConfig = {
  aiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
